version: "3.9"

services:
  api:
    build: ./Abeyonix_Backend/.
    container_name: abenyonix_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

    # Load env vars if you use them
    env_file:
      - ./Abeyonix_Backend/.env

    volumes:
      - ./Abeyonix_Backend:/app

    command: >
      gunicorn run:app
      --workers 4
      --worker-class uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:8000
      --timeout 120